name: midcurvenn
channels:
  - apple
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pytorch
  - torchvision 
  - torchaudio
  - numpy=1.24.*
  - pandas=2.1.*
  - matplotlib-base=3.8.*
  - pillow=10.1.*
  - jupyter=1.0.*
  - ipython=8.17.*
  - notebook=7.0.*
  - pip=23.3.*
  - python-dateutil=2.8.*
  - requests=2.31.*
  - setuptools=68.2.*
  - tqdm=4.66.*
  - pip:
    - tensorflow-macos==2.13.0
    - tensorflow-metal==1.0.1
    - torch-geometric
    - keras==2.13.1
    - huggingface-hub
    - transformers
    - datasets
    - drawsvg
    - imageio
    - opencv-python
    - matplotlib